name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Wybieramy gałąź, z której będą publikowane zmiany

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (jeśli używasz np. Jekyll lub innej technologii)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build the website (jeśli masz proces budowania)
        run: npm run build  # Przykład komendy budowania

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Wybieramy gałąź do publikacji
          folder: build     # Ścieżka do folderu z plikami strony
